### ISSUE TITLE
Error: Cannot find module 'eslint/lib/formatters/stylish'

### ISSUE THREAD

**Issue by davalapar** [webpack-contrib/eslint-loader#271]
problem:

eslint 5.x: `eslint/lib/formatters/stylish`
eslint 6.x: `eslint/lib/cli-engine/formatters/stylish`

solution:

```
        {
          enforce: 'pre',
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: [
            {
              loader: 'eslint-loader',
              options: {
                formatter: require('eslint/lib/cli-engine/formatters/stylish')
              },
            },
          ],
        },
```

**Comment by weilinzung** [comment]
update as default?

**Comment by vinayakkulkarni** [comment]
Yep, can confirm, issue happens with ESLint ^6.0, reverting back to version 5 resolves the issue.

```diff
- "eslint": "^6.0.1"
+ "eslint": "^5.16.0"
```

**Comment by rwieruch** [comment]
Confirm. Works with 5.16.0.  

`npm uninstall eslint && npm install eslint@5.16.0`

Related https://github.com/webpack-contrib/eslint-loader/issues/272 https://github.com/eslint/eslint/issues/11910

**Comment by ricardogobbosouza** [comment]
Resolved #275
Waiting a new version

**Comment by jtsom** [comment]
rebuilding with ESLint 6.0.1 still generates this error:
```
Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                       8:10:36 AM

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
Cannot find module 'eslint/lib/formatters/stylish'
Require stack:
- /Users/johntsombakos/Projects/interactivities-3/app/node_modules/eslint-loader/index.js
- /Users/johntsombakos/Projects/interactivities-3/app/node_modules/loader-runner/lib/loadLoader.js
- /Users/johntsombakos/Projects/interactivities-3/app/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/johntsombakos/Projects/interactivities-3/app/node_modules/thread-loader/dist/worker.js
    at PoolWorker.fromErrorObj (/Users/johntsombakos/Projects/interactivities-3/app/node_modules/thread-loader/dist/WorkerPool.js:258:12)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.module.exports (/Users/johntsombakos/Projects/interactivities-3/app/node_modules/eslint-loader/index.js:196:28)
```

**Comment by evilebottnawi** [comment]
Because it is still not published

**Comment by jtsom** [comment]
Looks like it was: 
https://github.com/webpack-contrib/eslint-loader/blob/master/CHANGELOG.md

**Comment by rcoundon** [comment]
Looks like github release has happened but not yet published to npm

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/eslint-loader/issues/281

**Comment by VimLeSai** [comment]
> Yep, can confirm, issue happens with ESLint ^6.0, reverting back to version 5 resolves the issue.
> 
> ```diff
> - "eslint": "^6.0.1"
> + "eslint": "^5.16.0"
> ```

@vinayakkulkarni Thanks. This works!

**Comment by brandonwie** [comment]
This was the only thing that worked. Thanks.

**Comment by gr790** [comment]
I added eslint-loader explicitly in dev dependencies and it solved the Issues.
