### ISSUE TITLE
 Could not load plugin @ typescript-eslint: cannot find module 'eslint-plugin-@typescript-eslint'

### ISSUE THREAD

**Issue by baixiaoji** [webpack-contrib/eslint-loader#287]
I reconfigure my project from tslint to eslint. I can start eslint manually, but the webpack does not start with this error message:
```bash
Module build failed (from /path/node_modules/eslint-loader/index.js):
Error: Failed to load plugin @typescript-eslint: Cannot find module 'eslint-plugin-@typescript-eslint'
```
I'm not sure if this is a major eslint-loader problem.
```js
module.exports = {
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint"],
  extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended", "plugin:react/recommended", "plugin:jest/recommended", "prettier", "prettier/@typescript-eslint"],
  rules: {
    "react/prop-types": false
  },
  parserOptions: {
    ecmaVersion: 6,
    project: "./tsconfig.json",
    sourceType: "module"
  },
settings: {
    react: {
      version: "detect"
    },
    linkComponents: [
      {"name": "Link", "linkAttribute": "href"}
    ]
  },
  env: {
    browser: true
  }
};

```
My .json package

```json
{
    "dependencies": {
        "@emotion/core": "10.0.6",
        "facepaint": "1.2.1",
        "react": "16.7.0",
        "react-dom": "16.7.0",
        "react-redux": "6.0.0",
        "redux": "4.0.1",
        "tslib": "1.9.3"
    },
    "devDependencies": {
        "@types/node": "10.12.21",
        "@types/react": "16.8.1",
        "@types/react-dom": "16.0.11",
        "@types/react-redux": "7.0.1",
        "@typescript-eslint/eslint-plugin": "1.2.0",
        "eslint": "5.13.0",
        "eslint-config-prettier": "4.0.0",
        "eslint-plugin-jest": "22.2.2",
        "eslint-plugin-react": "7.12.4",
        "tsconfig-paths-webpack-plugin": "3.2.0",
        "typescript": "3.2.1"
    }
}


```

**Comment by ricardogobbosouza** [comment]
@baixiaoji  I think your configuration is wrong
```js
module.exports = {
  ...
  plugins: ["@typescript-eslint"] // wrong
  plugins: ["@typescript-eslint/eslint-plugin"] // right
  ...
}

**Comment by baixiaoji** [comment]
> @baixiaoji I think your configuration is wrong
> 
> ```js
> module.exports = {
>   ...
>   plugins: ["@typescript-eslint"] // wrong
>   plugins: ["@typescript-eslint/eslint-plugin"] // right
>   ...
> }
> ```
i change the config, but having a new error
```
Failed to load plugin @typescript-eslint/eslint-plugin: Cannot find module '@typescript-eslint/eslint-plugin-eslint-plugin'
```

**Comment by baixiaoji** [comment]
@ricardogobbosouza 
finally, i find it's eslint plugin error in version 4.19, but I update to the 5.14 it's ok

**Comment by mi-mazouz** [comment]
not working with eslint version 6.1.0

**Comment by seedliu** [comment]
> not working with eslint version  @6.1.0

i reduce the version of eslint from 6.x.x to 5.14, it's worked

**Comment by jimmybrawn** [comment]
still problem here with 5.14

**Comment by FuzzyAtish** [comment]
> > not working with eslint version  @6.1.0
> 
> i reduce the version of eslint from 6.x.x to 5.14, it's worked

Same thing here.
After downgrading [eslint](https://github.com/eslint/eslint) from 6.6.0 to 5.14 it started working

**Comment by Sebastp** [comment]
Still, no fix doesn't work when downgrading eslint

**Comment by FuzzyAtish** [comment]
> Still, no fix doesn't work when downgrading eslint

Have you tried downgrading to version 5.x.x like @seedliu mentioned [above](https://github.com/webpack-contrib/eslint-loader/issues/287#issuecomment-547304036)
It's working for me with versions 5.14.1 and 5.16 too

**Comment by Sebastp** [comment]
> > Still, no fix doesn't work when downgrading eslint
> 
> Have you tried downgrading to version 5.x.x like @seedliu mentioned [above](https://github.com/webpack-contrib/eslint-loader/issues/287#issuecomment-547304036)
> It's working for me with versions 5.14.1 and 5.16 too

Yup,  5.14 and  6.5.1 doesn't work for me

**Comment by ricardogobbosouza** [comment]
Its works
Please see the documentation at https://github.com/typescript-eslint/typescript-eslint#how-do-i-configure-my-project-to-use-typescript-eslint

```json
// package.json
{
    "scripts": {
        "dev": "webpack"
    },
    "devDependencies": {
        "@typescript-eslint/eslint-plugin": "^2.6.1",
        "@typescript-eslint/parser": "^2.6.1",
        "eslint": "^6.6.0",
        "eslint-loader": "^3.0.2",
        "typescript": "^3.7.2",
        "webpack": "^4.41.2",
        "webpack-cli": "^3.3.10"
    }
}
```

```json
// .eslintrc
{
    "parser": "@typescript-eslint/parser",
    "plugins": ["@typescript-eslint"]
}
```

```js
// webpack.config.js
module.exports = {
    mode: "development",
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'eslint-loader'
            }
        ]
    }
}
```

**Comment by ricardogobbosouza** [comment]
Please, if any error occurs, provide a repository and step by step to reproduce

**Comment by FuzzyAtish** [comment]
Hello,
Sorry for the follow-up, I'm aware that the issue has been closed, I'd just like to share my experience.
For some reason, I was encountering this error within Visual Studio Code only when my project wasn't in the root folder of the project, i. e. there's a C# project, where the client side is separately included, but it's not the root.
Once I've reopened the project in VS Code as the root location, I didn't encounter the error.

**Comment by RahmatAliMalik5** [comment]
Error Still there. I am using `eslint` as global with one `.eslintrc.json` for all of my project. I am using `@typescript-eslint` to lint `.ts` files.

I have just installed fresh windows.
Installed `eslint` and `@typescript-eslint` globally.
Got error of `@typescript-eslint` not found as described previously here.
Came on this page. Checked the `eslint` verions, which was `6.8`.
Downgraded to `5.14` and working great.

My `.eslintrc.json` file is as follows:

```
{
  "env": {"browser": true, "node": true, "es6": true },
  "parser": "@typescript-eslint/parser",
  "extends": ["plugin:@typescript-eslint/recommended", "eslint:recommended"],
  "plugins": ["@typescript-eslint", "prettier"],
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts"],
      "@typescript-eslint": [".ts"]
    },
    "import/resolver": {
      "typescript": {}
    }
  },
  "overrides": [
    {
      // enable the rule specifically for TypeScript files
      "files": ["*.ts", "*.tsx"],
      "rules": {
        "@typescript-eslint/explicit-function-return-type": ["error"]
      }
    }
  ],
 rules: [ 
// lots of rules. Emitted for ease
]
}
```

**Comment by ricardogobbosouza** [comment]
@RahmatAliMalik5 
Please provide a repository and step by step to reproduce

**Comment by RahmatAliMalik5** [comment]
@ricardogobbosouza 
Thanks for your comment. I get error only when I use `eslint` as global by installing `eslint` and other packages globally by using `npm i -g`. I like to use only one `.eslintrc.json` file for all of my projects. Therefore, I am using global `eslint` settings in my Visual Studio Code.

The error maybe due to VS Code extension ESLint, I am using to lint automatically ([link of extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)).

I have tested it several times. Don't know why it comes only when I us latest version globally. It never comes when I use local `.eslintrc.json` or previous version `5.14` for global configuration.

**Comment by mkaufmaner** [comment]
> Hello,
> Sorry for the follow-up, I'm aware that the issue has been closed, I'd just like to share my experience.
> For some reason, I was encountering this error within Visual Studio Code only when my project wasn't in the root folder of the project, i. e. there's a C# project, where the client side is separately included, but it's not the root.
> Once I've reopened the project in VS Code as the root location, I didn't encounter the error.
> After correctly configuring VS Code, with the eslint.WorkingDirectories setting, everything was working fine

The following worked for me.

project.code-workspace
```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"eslint.workingDirectories": [
			{"mode": "auto"}
		]
	}
}
```

**Comment by ricardogobbosouza** [comment]
@RahmatAliMalik5 this is a change in eslint 6.
See https://eslint.org/docs/user-guide/migrating-to-6.0.0#plugins-and-shareable-configs-are-no-longer-affected-by-eslints

**Comment by renjithspace** [comment]
> Hello,
> Sorry for the follow-up, I'm aware that the issue has been closed, I'd just like to share my experience.
> For some reason, I was encountering this error within Visual Studio Code only when my project wasn't in the root folder of the project, i. e. there's a C# project, where the client side is separately included, but it's not the root.
> Once I've reopened the project in VS Code as the root location, I didn't encounter the error.
> After correctly configuring VS Code, with the eslint.WorkingDirectories setting, everything was working fine

This is the issue I'd been facing. I moved the source code to root of the project directory and it got fixed. @FuzzyAtish Thanks! ✌️

**Comment by zcq1933** [comment]
after i downgraded it it work succeed
1,npm uninstall eslint
2, sudo npm install --save-dev -g eslint@5.14
3,eslint --init

**Comment by zcq1933** [comment]
after i downgraded it it work succeed
1,npm uninstall eslint
2, sudo npm install --save-dev -g eslint@5.14
3,eslint --init

**Comment by seyfer** [comment]
if you run `eslint` from CLI there is a parameter `--resolve-plugins-relative-to /path` which could help you to point to your project root dir.
In my case, the problem was that we run `eslint` from the parent directory.

**Comment by giacomoalonzi** [comment]
I got the same error without any update, the same codebase as yesterday. 
`Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module 'typescript'`

I don't know what I have to do actually....

**Comment by vsakaria** [comment]
Node version to 12.x done it for me

**Comment by jotatoledo** [comment]
Related to https://github.com/typescript-eslint/typescript-eslint/issues/2100

**Comment by eeezae** [comment]
> Related to [typescript-eslint/typescript-eslint#2100](https://github.com/typescript-eslint/typescript-eslint/issues/2100)

`Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.json': Cannot find module 'typescript'`

Error still exists,  downgrade to version 3.0.0 or update to 3.0.3 alpha not work to me.

**Comment by tmhpfnr** [comment]
What I've found is, that when you run `npm ls` it says

```
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
```

So once I added the concrete dependency via `npm i --save-dev typescript@3.7.0-beta` it worked for me (I was using typescript globally before).

Hope that helps.

**Comment by samuel2749** [comment]
I had this problem too, I try to upgrade my node.js, and then it is been worked.
