### ISSUE TITLE
[Feature request] Support Eslint version 6

### ISSUE THREAD

**Issue by jimblue** [webpack-contrib/eslint-loader#272]
Hi,

ESlint 6 have been release, could you please add it to the peerDependencies, thank you.

https://github.com/webpack-contrib/eslint-loader/blob/02c1e76d9235823c6bb296ad68d74c99bfcc4445/package.json#L19

**Comment by milewski** [comment]
It looks like this loader breaks with eslint 6...

**Comment by jimblue** [comment]
Indeed I've just try. Renaming this issue to support ESlint 6

**Comment by graue** [comment]
Fixed in #275, but there's a need to update the CI configuration so it doesn't attempt to test with ESLint 6 on Node 6, since ESLint has dropped support for Node 6.

**Comment by platinumazure** [comment]
Hi everyone, I'm from ESLint.

Instead of doing a direct require to a formatter path, I would recommend `CLIEngine#getFormatter` (if you have a CLIEngine instance) or `CLIEngine.getFormatter` (static function you can use if you don't have an instance).

Requiring the path directly is not part of the public API and could change any time, even in patch releases. The two `CLIEngine` options are in the public API and won't change except in a major release (and then, only when absolutely needed and we can't deprecate).

Good luck! Please stop by our [Gitter chat](https://gitter.im/eslint/eslint) if you need help.

**Comment by vesper8** [comment]
related to https://github.com/vuejs/eslint-plugin-vue/issues/916

**Comment by rwieruch** [comment]
related https://github.com/eslint/eslint/issues/11910

**Comment by Mintonne** [comment]
Similar issue

```
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin 'import' declared in '.eslintrc.js » @vue/eslint-config-standard » C:\Users\Anon\Desktop\xxxx\node_modules\eslint-config-standard\index.js': Cannot find module 'eslint/lib/util/source-code'
```

![Annotation 2019-06-26 111816](https://user-images.githubusercontent.com/39894801/60163770-f6d5ab00-9804-11e9-85bd-1b5afbecac0a.jpg)

Works perfectly with 5.16.0

**Comment by ricardogobbosouza** [comment]
Hi @jimblue 
Resolved #275 , waiting a new version

**Comment by jimblue** [comment]
Sounds good 😄 
Waiting the new release to test it and close this issue.

**Comment by ahmadalfy** [comment]
@jimblue anything we can do to accelerate this process?

**Comment by saveman71** [comment]
@ahmadalfy I don't think @jimblue can do anything since he's just the issue reporte :sweat_smile: 

I guess tagging @MoOx who seem to be the one releasing the package on npm can help.

**Comment by MoOx** [comment]
See #264

**Comment by saveman71** [comment]
Sorry I missed that, didn't mean anything rude! Thanks for taking the time to reply.

**Comment by MoOx** [comment]
Don't worry, I just reopened this issue as it's still relevant as you can see.

**Comment by evilebottnawi** [comment]
Published https://www.npmjs.com/package/eslint-loader?activeTab=versions

**Comment by vesper8** [comment]
using

```
  "devDependencies": {
    "@babel/core": "latest",
    "@vue/cli-plugin-babel": "next",
    "@vue/cli-plugin-e2e-cypress": "next",
    "@vue/cli-plugin-eslint": "next",
    "@vue/cli-plugin-pwa": "next",
    "@vue/cli-plugin-unit-mocha": "next",
    "@vue/cli-service": "next",
    "@vue/eslint-config-airbnb": "latest",
    "@vue/test-utils": "latest",
    "chai": "latest",
    "eslint": "latest",
    "eslint-plugin-vue": "latest",
    "sass": "latest",
    "sass-loader": "latest",
    "vue-template-compiler": "latest"
  }
```

I am now getting a new error:

```
Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
Error: Cannot find module '/redacted/node_modules/eslint/lib/api.js/package.json'
```

using with `"eslint": "^5.0.0",` works
